// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqnAMK_OggIFdwELYiX21YVKMjyhEVk10',
    appId: '1:306365813646:web:0be744bbcf0e1210f6cadf',
    messagingSenderId: '306365813646',
    projectId: 'notifymeee',
    authDomain: 'notifymeee.firebaseapp.com',
    storageBucket: 'notifymeee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_p9e2CqfewxD1_oUV3ag6ACQTHc_DD88',
    appId: '1:306365813646:android:3dde2f5f35ab73f8f6cadf',
    messagingSenderId: '306365813646',
    projectId: 'notifymeee',
    storageBucket: 'notifymeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjbgs2Cb_RjSHCSowMD8jimVSMF9SVe-M',
    appId: '1:306365813646:ios:e48c3561add247bdf6cadf',
    messagingSenderId: '306365813646',
    projectId: 'notifymeee',
    storageBucket: 'notifymeee.appspot.com',
    iosClientId: '306365813646-jhgg22bfaagqon1s44m9f8vmm0n3j0cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifymeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjbgs2Cb_RjSHCSowMD8jimVSMF9SVe-M',
    appId: '1:306365813646:ios:e48c3561add247bdf6cadf',
    messagingSenderId: '306365813646',
    projectId: 'notifymeee',
    storageBucket: 'notifymeee.appspot.com',
    iosClientId: '306365813646-jhgg22bfaagqon1s44m9f8vmm0n3j0cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifymeee',
  );
}
